language: node_js
node_js:
  - "11"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - npm install

script:
- npm run lint
- npm run test-headless
- npm run build
- mv dist/VipPWA/index.html dist/VipPWA/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/VipPWA
  on:
    branch: master